stages:
  - install
  - build

Install:
  stage: install
  image: node:18
  script:
    - npm install
  cache:
    policy: push
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"
    

Build:
  stage: build
  image: node:18
  script:
   - npm run build
  cache:
    policy: pull
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"