stages:
  - install deps
  - build

install:
  stage: install deps
  image: node:22
  script: 
   - npm install
  cache: 
   policy: push
   key: $CI_COMMIT_REF_SLUG
   paths: 
    - "./node_modules"

build:
  stage: build
  image: node:22
  script: 
   - "node app.js"
  cache:
   policy: pull
   key: $CI_COMMIT_REF_SLUG
   paths:
     - "./node_modules"
