stages:
  - install
  - build
  - docker_build
  - deploy

Install:
  stage: install
  image: node:18
  script:
    - cd frontend
    - npm install
  cache:
    policy: push
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"

Build:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm run build
  cache:
    policy: pull
    key: $CI_COMMIT_REF_SLUG
    paths:
      - "frontend/node_modules"

Docker_build:
  stage: docker_build
  services:
    - docker:dind
  variables:
    IMAGE_NAME: tik217/frontend
  script:
    - docker login -u tik217 -p ${DOCKER_PWD}
    - docker build -f frontend.Dockerfile -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}

Deploy:
  stage: deploy
  image: ringcentral/sshpass
  script:
   - sshpass ssh ${SSH_HOST} -p ${SSH_PASS} "\
    cd ci-cd
    git pull
    docker compose pull nginx
    docker compose stop nginx
    docker compose up -d nginx
    "