stages:
  - install
  - build
  - docker_build
  - deploy

Install:
  stage: install
  image: node:18
  script:
    - cd frontend
    - npm install
  cache:
    policy: push
    key: ${CI_COMMIT_REF_SLUG}-modules
    paths:
      - "frontend/node_modules"

Build:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm run build
  cache:
    - key: ${CI_COMMIT_REF_SLUG}-modules
      policy: pull
      paths:
        - "frontend/node_modules"
    - key:  ${CI_COMMIT_REF_SLUG}-build
      policy: push
      paths:
        - "frontend/build"

Docker_build:
  stage: docker_build
  image: docker
  services:
    - docker:dind
  variables:
    IMAGE_NAME: tik217/frontend
  script:
    - docker login -u tik217 -p ${DOCKER_PWD}
    - docker build -f frontend.Dockerfile -t ${IMAGE_NAME} .
    - docker push ${IMAGE_NAME}
  cache:
    key:  ${CI_COMMIT_REF_SLUG}-build
    policy: pull
    paths:
      - "frontend/build"

Deploy:
  stage: deploy
  image: ringcentral/sshpass
  script:
   - sshpass -p tplink6e4458 ssh 213.171.9.207 -o stricthostkeychecking=no "\
      cd ci-cd &&
      git pull &&
      docker compose pull nginx &&
      docker compose stop nginx &&
      docker compose up -d nginx
    "