version: '3.7'

services:
  environment:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - 3005:3005
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node app.js