version: "3.7"

services:
  environment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node app.js
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/etc/letsencrypt
